### ISSUE TITLE
Add (sub)chapter to RDM section

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/repro-book#10]
- [x] Chapter on rectangular / tidy data
- [x] https://better-spreadsheets.netlify.app, [Broman & Woo, 2018](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989)
- [x] Modularity? $\rightarrow$ see #44 
- [x] FAIR principles
- [x] Data Standards (why, benefits)
- [x] e.g., Brain Imaging Data Strcuture (see #39)
- [x] Psych-DS (https://psychds-docs.readthedocs.io/en/latest/)
- [x] Using a codebook / json files
- [x] Reinhard & Rogoff Story $\rightarrow$ [News article BBC](https://www.bbc.com/news/magazine-22223190), [News Article NewYorkTimes](https://archive.nytimes.com/economix.blogs.nytimes.com/2013/04/16/flaws-are-cited-in-a-landmark-study-on-debt-and-growth/?smid=tw-share&_r=0), [Reinhart & Rogoff, 2010](http://www.aeaweb.org/articles.php?doi=10.1257/aer.100.2.573), [Herndon et al., 2014](https://doi.org/10.1093/cje/bet075)
> Most important point of the stories: They shared the raw data and so the error could be found and fixed.

> on why to stop using Excel

- [x] Renaming of genes
- [x] https://glammr.us/@platypus/112875845148179201

**Comment by justus-reihs** [comment]
Closed by merging #38.
Remaining open tasks in #39 and #45
