### ISSUE TITLE
Add Justus Reihs as author

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/repro-book#18]
I would like to add @justus-reihs as an author.

To do this, add Justus as an author in the `_authors.yml` file (see [here](https://github.com/lnnrtwttkhn/repro-book/blob/main/_authors.yml)).

For details, see the Quarto documentation [here](https://quarto.org/docs/journals/authors.html).

Would you like to tackle this @justus-reihs and add yourself?

**Comment by justus-reihs** [comment]
I'm on it
